name: Test suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-static-current:
    strategy:
      fail-fast: false
      matrix:
        puppet: [7.22.0]
        ruby: [2.7.7, 3.0.5, 3.1.3]

    name: Static code analysis
    runs-on: ubuntu-20.04
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
      env:
        PUPPET_VERSION: ${{ matrix.puppet }}

    - name: Run list tasks
      run: |
        PUPPET_VERSION=${{ matrix.puppet }} bundle exec rake --tasks

